cd source/3rdparty/Debug
make clean
cd ../../..
cd source/3rdparty/Release
make clean
cd ../../..
cd source/cccommon/Debug
make clean
cd ../../..
cd source/cccommon/Release
make clean
cd ../../..
cd source/cclib/Debug
make clean
cd ../../..
cd source/cclib/Release
make clean
cd ../../..
cd source/ccdll/Debug
make clean
cd ../../..
cd source/ccdll/Release
make clean
cd ../../..
cd source/ccnode/Debug
make clean
cd ../../..
cd source/ccnode/Release
make clean
cd ../../..
cd source/cctracker/Debug
make clean
cd ../../..
cd source/cctracker/Release
make clean
cd ../../..